### ISSUE TITLE
Bot problem

### ISSUE THREAD

**Issue by daszyja** [joachimvalente/bogame2#1]
Hi, after scan bot crashing, do u know why? 

> [INFO] 2018-12-19 22:39:44: Potential target: 1:116:4 [obama] - obama (i) (rank 935)
[INFO] 2018-12-19 22:39:44: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:44: Potential target: 1:116:6 [Planeta Pri...] - Renegade G... (i) (rank 1478)
[INFO] 2018-12-19 22:39:44: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:44: Navigating to 1:84
[INFO] 2018-12-19 22:39:48: 0 ongoing missions
[INFO] 2018-12-19 22:39:48: 0 total scans
[INFO] 2018-12-19 22:39:48: Inspecting [1:84]...
[INFO] 2018-12-19 22:39:55: Found 8 players
[INFO] 2018-12-19 22:39:55: Adding inactive player
[INFO] 2018-12-19 22:39:55: Adding inactive player
[INFO] 2018-12-19 22:39:55: Adding honorable player
[INFO] 2018-12-19 22:39:55: Adding inactive player
[INFO] 2018-12-19 22:39:55: Adding honorable player
[INFO] 2018-12-19 22:39:55: Adding normal player
[INFO] 2018-12-19 22:39:55: Adding honorable player
[INFO] 2018-12-19 22:39:55: Found 7 potential targets
[INFO] 2018-12-19 22:39:56: Potential target: 1:84:4 [Planeta Pri...] - Sovereign ... (i) (rank 1287)
[INFO] 2018-12-19 22:39:56: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:57: Potential target: 1:84:6 [Planeta Pri...] - Commodore ... (i) (rank 1195)
[INFO] 2018-12-19 22:39:57: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:57: Potential target: 1:84:7 [Belo Horizo...] - JaderCM (PH) (rank 8)
[INFO] 2018-12-19 22:39:57: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:58: Potential target: 1:84:8 [Planeta Pri...] - Sovereign ... (i) (rank 1654)
[INFO] 2018-12-19 22:39:58: Skipping (outside allowed rank bounds)
[INFO] 2018-12-19 22:39:59: Potential target: 1:84:9 [Shemsu Hor I] - Czar Stard... (PH) (rank 46)
[INFO] 2018-12-19 22:39:59: Skipping (outside allowed rank bounds)
Traceback (most recent call last):
  File "scan.py", line 267, in <module>
    main()
  File "scan.py", line 263, in main
    scan(b, args)
  File "scan.py", line 56, in scan
    args)
  File "scan.py", line 185, in inspect
    for tooltip in sln.finds(b, By.ID, player_id):
  File "C:\Users\Dawid\Downloads\bogame2-master\bogame2-master\selenium_lib.py", line 47, in finds
    EC.presence_of_all_elements_located((by, element)))
  File "C:\Users\Dawid\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)

**Comment by joachimvalente** [comment]
Hi Dawid! Yeah sorry that logic is a bit brittle. You can try again, sometimes it just works, or add timeout_ok=True on line 185:

`for tooltip in sln.finds(b, By.ID, player_id, timeout_ok=True): ...`

**Comment by daszyja** [comment]
Well, i found the exactly problem why it's crashing.

All it's ok, just when some1 abadon his planet. Then it's crashing your, when i add timeout_ok=True, it took a bit time but after about minute he's skipping it.

**Comment by daszyja** [comment]
anyway another question, is there way to spy moons too?

**Comment by joachimvalente** [comment]
No just planets for now.
